In [1]:
import numpy as np
import pandas as pd
from girth import grm_jml, condition_polytomous_response
from girth import tag_missing_data, validate_estimation_options
from girth.synthetic import create_synthetic_irt_polytomous

In [48]:
df = pd.read_csv('DPQ_H.csv')

In [7]:
def filter_rows(df, cutoff):
    tot_cols = df.shape[1]
    print("original number of rows: ", df.shape[0])
    df = df[df.isnull().sum(axis=1) < tot_cols*cutoff]
    print("remaining rows: ", df.shape[0])
    return df

In [50]:
df.drop(['SEQN'], axis = 1, inplace=True)
df = filter_rows(df, cutoff=0.8)
df.fillna(df.mode().iloc[0], inplace=True)
df = df.astype(int)
df = df.replace([7, 9], 3)
df += 1

original number of rows:  5924
remaining rows:  5395


In [96]:
df.head()

DPQ010  DPQ020  DPQ030  DPQ040  DPQ050  DPQ060  DPQ070  DPQ080  DPQ090  \
0       2       1       1       1       1       1       1       1       1   
1       3       1       1       1       1       1       1       1       1   
2       1       1       1       1       1       1       1       1       1   
3       3       2       1       4       4       1       1       1       1   
4       4       4       4       4       4       2       3       2       1   

   DPQ100  
0       2  
1       1  
2       1  
3       2  
4       4

In [75]:
nd_array_input = df[:].values

In [76]:
print(nd_array_input[0:5, :])

[[2 1 1 1 1 1 1 1 1 2]
 [3 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [3 2 1 4 4 1 1 1 1 2]
 [4 4 4 4 4 2 3 2 1 4]]


In [87]:
np.unique(nd_array_input)

array([1, 2, 3, 4])

In [88]:

estimated_parameters = grm_jml(nd_array_input)

In [95]:
print(estimated_parameters['Difficulty'][0:5, :])

[[ 4.23945222         nan         nan]
 [ 3.20435814         nan         nan]
 [ 6.                 nan         nan]
 [ 0.14982367  0.46418826  0.68770248]
 [-1.57584633 -0.16143177  0.04549995]]
